# Generated by Django 5.1.3 on 2024-11-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_application_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='design_image',
            field=models.ImageField(blank=True, null=True, upload_to='designs/'),
        ),
    ]
